name: Test Pull Requests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Cache Bundler dependencies
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Bundler and Dependencies
        run: |
          gem install bundler -v 2.3.26
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --config _prod.yml

      - name: Run HTML Proofer tests
        run: bundle exec htmlproofer ./_site --disable-external
