name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Cache Bundler dependencies
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Bundler and Dependencies
        run: |
          gem install bundler -v 2.3.26
          bundle install

      - name: Add SSH Deploy Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Build Jekyll site
        run: bundle exec jekyll build --config _prod.yml

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: rsync --delete -avP -e "ssh -p $PORT" ./_site/ $USER@$HOST:/var/www/html/
